name: memochat
description: A modern cross-platform messaging application.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_messaging: 16.2.0
  flutter_local_notifications: ^19.5.0
  audioplayers: ^6.1.0
  vibration: ^2.0.1
  livekit_client: 2.2.5
  flutter_webrtc: 0.11.7
  shared_preferences: ^2.3.5
  file_picker: ^9.2.3
  http: ^1.2.2
  dio: ^5.8.0+1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  record: ^6.0.0
  sqflite: ^2.4.1
  connectivity_plus: ^6.1.4
  path_provider: ^2.1.5
  path: ^1.9.0
  firebase_storage: ^13.0.4
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  fluttertoast: ^8.2.12
  photo_manager: ^3.6.4
  workmanager: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icon/
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/icon_app.png
  adaptive_icon_background: "#0A8F83"
  adaptive_icon_foreground: assets/icon/icon_app.png
  min_sdk_android: 21
