name: memochat
description: A modern cross-platform messaging application.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_messaging: 16.2.0
  flutter_local_notifications: ^19.5.0
  livekit_client: 2.3.6
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/icon_app.png
  adaptive_icon_background: "#0A8F83"
  adaptive_icon_foreground: assets/icon/icon_app.png
  min_sdk_android: 21
