import 'dart:io';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';
import '../data/social_service.dart';

class SocialScreen extends StatefulWidget{const SocialScreen({super.key,this.service});final SocialService? service;@override State<SocialScreen> createState()=>_SocialScreenState();}
class _SocialScreenState extends State<SocialScreen> with SingleTickerProviderStateMixin{late final SocialService service=widget.service??SocialService();late final TabController tabs=TabController(length:2,vsync:this);@override void dispose(){tabs.dispose();super.dispose();}void compose()=>showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>_Composer(service:service));
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Memo',style:TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(tooltip:'بحث',onPressed:()=>showSearch(context:c,delegate:_Search()),icon:const Icon(Icons.search_rounded)),IconButton(tooltip:'النشاط',onPressed:()=>showDialog(context:c,builder:(_)=>const AlertDialog(title:Text('نشاط Memo'),content:Text('الإعجابات والتعليقات والمشاركات والمتابعات ستظهر هنا.'))),icon:const Icon(Icons.notifications_none_rounded))],bottom:TabBar(controller:tabs,tabs:const[Tab(icon:Icon(Icons.dynamic_feed_rounded),text:'المنشورات'),Tab(icon:Icon(Icons.play_circle_outline_rounded),text:'الريلز')])),body:TabBarView(controller:tabs,children:[_Feed(service:service),_Reels(service:service)]),floatingActionButton:FloatingActionButton.extended(onPressed:compose,icon:const Icon(Icons.add_rounded),label:const Text('إنشاء')));
}
class _Feed extends StatelessWidget{const _Feed({required this.service});final SocialService service;@override Widget build(BuildContext c)=>StreamBuilder(stream:service.posts(),builder:(c,s){if(s.hasError)return const Center(child:Text('تعذر تحميل المنشورات.'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final d=s.data!.docs;if(d.isEmpty)return const Center(child:Text('لا توجد منشورات بعد. كن أول من ينشر في Memo.'));return ListView.builder(padding:const EdgeInsets.fromLTRB(12,12,12,100),itemCount:d.length,itemBuilder:(_,i)=>_Post(service:service,id:d[i].id,data:d[i].data()));});}
class _Post extends StatelessWidget{const _Post({required this.service,required this.id,required this.data});final SocialService service;final String id;final Map<String,dynamic> data;@override Widget build(BuildContext c){final url=data['mediaUrl']?.toString()??'';final video=data['mediaType']=='video';return Card(clipBehavior:Clip.antiAlias,margin:const EdgeInsets.only(bottom:12),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[ListTile(leading:const CircleAvatar(child:Icon(Icons.person_rounded)),title:Text(data['authorId']?.toString()??'مستخدم Memo',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('منشور على Memo')),if(url.isNotEmpty)(video?AspectRatio(aspectRatio:16/9,child:_Video(url)):CachedNetworkImage(imageUrl:url,height:270,fit:BoxFit.cover)),if((data['text']?.toString()??'').isNotEmpty)Padding(padding:const EdgeInsets.all(16),child:Text(data['text'].toString(),style:const TextStyle(fontSize:16,height:1.45))),_Actions(service:service,collection:'socialPosts',id:id,data:data)]));}}
class _Reels extends StatelessWidget{const _Reels({required this.service});final SocialService service;@override Widget build(BuildContext c)=>StreamBuilder(stream:service.reels(),builder:(c,s){if(s.hasError)return const Center(child:Text('تعذر تحميل الريلز.'));if(!s.hasData)return const Center(child:CircularProgressIndicator());final d=s.data!.docs;if(d.isEmpty)return const Center(child:Text('لا توجد ريلز بعد.'));return PageView.builder(scrollDirection:Axis.vertical,itemCount:d.length,itemBuilder:(_,i)=>_Reel(service:service,id:d[i].id,data:d[i].data()));});}}
class _Reel extends StatelessWidget{const _Reel({required this.service,required this.id,required this.data});final SocialService service;final String id;final Map<String,dynamic> data;@override Widget build(BuildContext c)=>Stack(fit:StackFit.expand,children:[_Video(data['videoUrl']?.toString()??'',cover:true),Positioned(right:12,bottom:20,left:12,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(data['caption']?.toString()??'',style:const TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w800)),_Actions(service:service,collection:'socialReels',id:id,data:data,light:true)]))]);}
class _Video extends StatefulWidget{const _Video(this.url,{this.cover=false});final String url;final bool cover;@override State<_Video> createState()=>_VideoState();}
class _VideoState extends State<_Video>{VideoPlayerController? p;@override void initState(){super.initState();if(widget.url.isNotEmpty){p=VideoPlayerController.networkUrl(Uri.parse(widget.url))..initialize().then((_){if(mounted)setState((){});p?.setLooping(true);p?.play();});}}@override void dispose(){p?.dispose();super.dispose();}@override Widget build(BuildContext c){final x=p;if(x==null||!x.value.isInitialized)return const Center(child:CircularProgressIndicator());return FittedBox(fit:widget.cover?BoxFit.cover:BoxFit.contain,child:SizedBox(width:x.value.size.width,height:x.value.size.height,child:VideoPlayer(x)));}}
class _Actions extends StatelessWidget{const _Actions({required this.service,required this.collection,required this.id,required this.data,this.light=false});final SocialService service;final String collection,id;final Map<String,dynamic> data;final bool light;@override Widget build(BuildContext c){final color=light?Colors.white:Theme.of(c).colorScheme.onSurface;final author=data['authorId']?.toString()??'';return Row(children:[StreamBuilder(stream:service.like(collection,id),builder:(c,s){final liked=s.data?.exists==true;return Row(children:[IconButton(color:liked?Colors.red:color,onPressed:()=>service.toggleLike(collection,id,liked),icon:Icon(liked?Icons.favorite_rounded:Icons.favorite_border_rounded)),Text((data['likesCount']??0).toString(),style:TextStyle(color:color))]);}),IconButton(color:color,onPressed:()=>_comments(c),icon:const Icon(Icons.mode_comment_outlined)),Text((data['commentsCount']??0).toString(),style:TextStyle(color:color)),IconButton(color:color,onPressed:()=>service.share(collection:collection,id:id),icon:const Icon(Icons.share_rounded)),StreamBuilder(stream:service.saved(id),builder:(c,s){final saved=s.data?.exists==true;return IconButton(color:color,onPressed:()=>service.toggleSave(collection,id,saved),icon:Icon(saved?Icons.bookmark_rounded:Icons.bookmark_border_rounded));}),const Spacer(),if(author.isNotEmpty)StreamBuilder(stream:service.following(author),builder:(c,s){final f=s.data?.exists==true;return TextButton(onPressed:()=>service.toggleFollow(author,f),child:Text(f?'متابَع':'متابعة',style:TextStyle(color:color)));})]);}
Future<void> _comments(BuildContext c)async{final input=TextEditingController();await showModalBottomSheet(context:c,isScrollControlled:true,showDragHandle:true,builder:(ctx)=>SafeArea(child:SizedBox(height:MediaQuery.sizeOf(ctx).height*.72,child:Column(children:[const Padding(padding:EdgeInsets.all(16),child:Text('التعليقات',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900))),Expanded(child:StreamBuilder(stream:service.comments(collection,id),builder:(c,s){final d=s.data?.docs??const[];return d.isEmpty?const Center(child:Text('كن أول من يعلّق.')):ListView.builder(itemCount:d.length,itemBuilder:(_,i)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(d[i].data()['userId']?.toString()??''),subtitle:Text(d[i].data()['text']?.toString()??'')));})),Padding(padding:EdgeInsets.fromLTRB(12,8,12,MediaQuery.viewInsetsOf(ctx).bottom+8),child:Row(children:[Expanded(child:TextField(controller:input,maxLength:1000,decoration:const InputDecoration(hintText:'اكتب تعليقًا...'))),IconButton(onPressed:()async{await service.comment(collection,id,input.text);input.clear();},icon:const Icon(Icons.send_rounded))]))])));input.dispose();}}
class _Composer extends StatefulWidget{const _Composer({required this.service});final SocialService service;@override State<_Composer> createState()=>_ComposerState();}
class _ComposerState extends State<_Composer>{final text=TextEditingController();final picker=ImagePicker();File? media;bool reel=false,busy=false;@override void dispose(){text.dispose();super.dispose();}Future<void> image()async{final x=await picker.pickImage(source:ImageSource.gallery,imageQuality:88);if(x!=null&&mounted)setState(()=>media=File(x.path));}Future<void> video()async{final x=await picker.pickVideo(source:ImageSource.gallery,maxDuration:const Duration(seconds:90));if(x!=null&&mounted)setState(()=>media=File(x.path));}Future<void> publish()async{if(media==null&&text.text.trim().isEmpty)return;setState(()=>busy=true);try{if(reel){if(media==null)throw StateError('اختر فيديو للريل');await widget.service.createReel(video:media!,caption:text.text);}else{await widget.service.createPost(text:text.text,media:media,video:media!=null&&RegExp(r'\.(mp4|mov|m4v)$',caseSensitive:false).hasMatch(media!.path));}if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر النشر: '+e.toString())));}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Padding(padding:EdgeInsets.fromLTRB(16,10,16,MediaQuery.viewInsetsOf(c).bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('إنشاء محتوى في Memo',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),SegmentedButton<bool>(segments:const[ButtonSegment(value:false,label:Text('منشور'),icon:Icon(Icons.article_outlined)),ButtonSegment(value:true,label:Text('ريل'),icon:Icon(Icons.video_library_outlined))],selected:{reel},onSelectionChanged:(v)=>setState(()=>reel=v.first)),TextField(controller:text,maxLength:5000,maxLines:5,decoration:const InputDecoration(hintText:'ما الذي تريد مشاركته؟')),const SizedBox(height:8),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:reel?video:image,icon:Icon(reel?Icons.video_library_rounded:Icons.photo_library_rounded),label:Text(reel?'اختيار فيديو':'اختيار صورة'))),if(!reel)...[const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:video,icon:const Icon(Icons.videocam_outlined),label:const Text('فيديو')))]),if(media!=null)Padding(padding:const EdgeInsets.all(8),child:Text(media!.path.split(Platform.pathSeparator).last,maxLines:1,overflow:TextOverflow.ellipsis)),FilledButton.icon(onPressed:busy?null:publish,icon:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.publish_rounded),label:Text(busy?'جارٍ النشر...':'نشر'))]));}
class _Search extends SearchDelegate<void>{@override List<Widget>?buildActions(BuildContext c)=>[IconButton(onPressed:()=>query='',icon:const Icon(Icons.clear))];@override Widget?buildLeading(BuildContext c)=>BackButton(onPressed:()=>close(c,null));@override Widget buildResults(BuildContext c)=>Center(child:Text(query.isEmpty?'ابحث عن أشخاص ومنشورات':'بحث Memo: '+query));@override Widget buildSuggestions(BuildContext c)=>buildResults(c);}
