import 'package:flutter/widgets.dart';
import '../models/game.dart';
import 'games/color_rush_game.dart';import 'games/higher_lower_game.dart';import 'games/number_guess_game.dart';import 'games/word_scramble_game.dart';import 'games/emoji_memory_game.dart';import 'games/pattern_tap_game.dart';import 'games/odd_one_out_game.dart';import 'games/four_in_row_game.dart';import 'games/dots_and_boxes_game.dart';import 'games/reaction_race_game.dart';import 'games/card_flip_game.dart';import 'games/treasure_hunt_game.dart';import 'games/maze_runner_game.dart';import 'games/stack_tower_game.dart';import 'games/target_hit_game.dart';import 'games/bubble_pop_game.dart';import 'games/color_match_game.dart';import 'games/shape_match_game.dart';import 'games/sequence_recall_game.dart';import 'games/fast_choice_game.dart';import 'games/true_false_game.dart';import 'games/flag_quiz_game.dart';import 'games/animal_quiz_game.dart';import 'games/food_quiz_game.dart';import 'games/geography_game.dart';import 'games/science_game.dart';import 'games/history_game.dart';import 'games/language_game.dart';import 'games/riddle_rush_game.dart';import 'games/anagram_battle_game.dart';import 'games/math_duel_game.dart';import 'games/code_breaker_game.dart';import 'games/light_switch_game.dart';import 'games/connect_pairs_game.dart';import 'games/word_guess_game.dart';import 'games/picture_puzzle_game.dart';import 'games/balance_beam_game.dart';import 'games/rocket_race_game.dart';import 'games/galaxy_catch_game.dart';import 'games/rhythm_tap_game.dart';

class DedicatedGameFactory {
  static Widget? build(GameType t){
    switch(t){
      case GameType.colorRush:return ColorRushGame();case GameType.higherLower:return HigherLowerGame();case GameType.numberGuess:return NumberGuessGame();case GameType.wordScramble:return WordScrambleGame();case GameType.emojiMemory:return EmojiMemoryGame();case GameType.patternTap:return PatternTapGame();case GameType.oddOneOut:return OddOneOutGame();case GameType.fourInRow:return FourInRowGame();case GameType.dotsAndBoxes:return DotsAndBoxesGame();case GameType.reactionRace:return ReactionRaceGame();case GameType.cardFlip:return CardFlipGame();case GameType.treasureHunt:return TreasureHuntGame();case GameType.mazeRunner:return MazeRunnerGame();case GameType.stackTower:return StackTowerGame();case GameType.targetHit:return TargetHitGame();case GameType.bubblePop:return BubblePopGame();case GameType.colorMatch:return ColorMatchGame();case GameType.shapeMatch:return ShapeMatchGame();case GameType.sequenceRecall:return SequenceRecallGame();case GameType.fastChoice:return FastChoiceGame();case GameType.trueFalse:return TrueFalseGame();case GameType.flagQuiz:return FlagQuizGame();case GameType.animalQuiz:return AnimalQuizGame();case GameType.foodQuiz:return FoodQuizGame();case GameType.geographyQuiz:return GeographyGame();case GameType.scienceQuiz:return ScienceGame();case GameType.historyQuiz:return HistoryGame();case GameType.languageQuiz:return LanguageGame();case GameType.riddleRush:return RiddleRushGame();case GameType.anagramBattle:return AnagramBattleGame();case GameType.mathDuel:return MathDuelGame();case GameType.codeBreaker:return CodeBreakerGame();case GameType.lightSwitch:return LightSwitchGame();case GameType.connectPairs:return ConnectPairsGame();case GameType.wordGuess:return WordGuessGame();case GameType.picturePuzzle:return PicturePuzzleGame();case GameType.balanceBeam:return BalanceBeamGame();case GameType.rocketRace:return RocketRaceGame();case GameType.galaxyCatch:return GalaxyCatchGame();case GameType.rhythmTap:return RhythmTapGame();default:return null;
    }
  }
}