import 'package:flutter/widgets.dart';
import '../models/game.dart';
import 'games/color_rush_game.dart';import 'games/higher_lower_game.dart';import 'games/number_guess_game.dart';import 'games/word_scramble_game.dart';import 'games/emoji_memory_game.dart';import 'games/pattern_tap_game.dart';import 'games/odd_one_out_game.dart';import 'games/four_in_row_game.dart';import 'games/dots_and_boxes_game.dart';import 'games/reaction_race_game.dart';import 'games/card_flip_game.dart';import 'games/treasure_hunt_game.dart';import 'games/maze_runner_game.dart';import 'games/stack_tower_game.dart';import 'games/target_hit_game.dart';import 'games/bubble_pop_game.dart';import 'games/color_match_game.dart';import 'games/shape_match_game.dart';import 'games/sequence_recall_game.dart';import 'games/fast_choice_game.dart';import 'games/true_false_game.dart';import 'games/flag_quiz_game.dart';import 'games/animal_quiz_game.dart';import 'games/food_quiz_game.dart';import 'games/geography_game.dart';import 'games/science_game.dart';import 'games/history_game.dart';import 'games/language_game.dart';import 'games/riddle_rush_game.dart';import 'games/anagram_battle_game.dart';import 'games/math_duel_game.dart';import 'games/code_breaker_game.dart';import 'games/light_switch_game.dart';import 'games/connect_pairs_game.dart';import 'games/word_guess_game.dart';import 'games/picture_puzzle_game.dart';import 'games/balance_beam_game.dart';import 'games/rocket_race_game.dart';import 'games/galaxy_catch_game.dart';import 'games/rhythm_tap_game.dart';

class DedicatedGameFactory {
  static Widget? build(GameType t){
    switch(t){
      case GameType.colorRush:return const ColorRushGame();case GameType.higherLower:return const HigherLowerGame();case GameType.numberGuess:return const NumberGuessGame();case GameType.wordScramble:return const WordScrambleGame();case GameType.emojiMemory:return const EmojiMemoryGame();case GameType.patternTap:return const PatternTapGame();case GameType.oddOneOut:return const OddOneOutGame();case GameType.fourInRow:return const FourInRowGame();case GameType.dotsAndBoxes:return const DotsAndBoxesGame();case GameType.reactionRace:return const ReactionRaceGame();case GameType.cardFlip:return const CardFlipGame();case GameType.treasureHunt:return const TreasureHuntGame();case GameType.mazeRunner:return const MazeRunnerGame();case GameType.stackTower:return const StackTowerGame();case GameType.targetHit:return const TargetHitGame();case GameType.bubblePop:return const BubblePopGame();case GameType.colorMatch:return const ColorMatchGame();case GameType.shapeMatch:return const ShapeMatchGame();case GameType.sequenceRecall:return const SequenceRecallGame();case GameType.fastChoice:return const FastChoiceGame();case GameType.trueFalse:return const TrueFalseGame();case GameType.flagQuiz:return const FlagQuizGame();case GameType.animalQuiz:return const AnimalQuizGame();case GameType.foodQuiz:return const FoodQuizGame();case GameType.geographyQuiz:return const GeographyGame();case GameType.scienceQuiz:return const ScienceGame();case GameType.historyQuiz:return const HistoryGame();case GameType.languageQuiz:return const LanguageGame();case GameType.riddleRush:return const RiddleRushGame();case GameType.anagramBattle:return const AnagramBattleGame();case GameType.mathDuel:return const MathDuelGame();case GameType.codeBreaker:return const CodeBreakerGame();case GameType.lightSwitch:return const LightSwitchGame();case GameType.connectPairs:return const ConnectPairsGame();case GameType.wordGuess:return const WordGuessGame();case GameType.picturePuzzle:return const PicturePuzzleGame();case GameType.balanceBeam:return const BalanceBeamGame();case GameType.rocketRace:return const RocketRaceGame();case GameType.galaxyCatch:return const GalaxyCatchGame();case GameType.rhythmTap:return const RhythmTapGame();default:return null;
    }
  }
}