// ignore_for_file: prefer_interpolation_to_compose_strings
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import '../../../core/offline/pending_message_queue.dart';
import '../../../core/media/nextcloud_media_service.dart';
import '../../calls/presentation/call_screen.dart';

class ChatRoomScreen extends StatefulWidget {
  const ChatRoomScreen({super.key,required this.chatId,required this.otherUserId,required this.otherUserName,this.otherUserImage});
  final String chatId,otherUserId,otherUserName; final String? otherUserImage;
  @override State<ChatRoomScreen> createState()=>_ChatRoomScreenState();
}
class _ChatRoomScreenState extends State<ChatRoomScreen> with WidgetsBindingObserver{
  final _pending=PendingMessageQueue();
  final _text=TextEditingController();final _scroll=ScrollController();final _db=FirebaseFirestore.instance;final _media=const NextcloudMediaService();Timer? _typingTimer;bool _typing=false,_uploading=false;Map<String,dynamic>? _reply;
  String get _uid=>FirebaseAuth.instance.currentUser?.uid??'';
  CollectionReference<Map<String,dynamic>> get _messages=>_db.collection('chats').doc(widget.chatId).collection('messages');
  @override void initState(){super.initState();WidgetsBinding.instance.addObserver(this);_text.addListener(_onText);_flushPending();}
  @override void didChangeAppLifecycleState(AppLifecycleState state){if(state==AppLifecycleState.resumed)_flushPending();}
  Future<void> _flushPending() async {await _pending.flush((message) async {final ref=_messages.doc(message.id);await ref.set({'chatId':widget.chatId,'senderId':_uid,'senderName':FirebaseAuth.instance.currentUser?.displayName??'مستخدم','text':message.text,'type':'text','status':'sent','timestamp':Timestamp.fromDate(message.createdAt),'clientTimestamp':message.createdAt.microsecondsSinceEpoch});});}
  void _onText(){if(_text.text.isNotEmpty&&!_typing)_setTyping(true);_typingTimer?.cancel();_typingTimer=Timer(const Duration(seconds:2),()=>_setTyping(false));}
  Future<void> _setTyping(bool value)async{if(_typing==value)return;if(mounted)setState(()=>_typing=value);try{await _db.collection('chats').doc(widget.chatId).set({'typing.$_uid':value},SetOptions(merge:true));}catch(_){await _pending.enqueue(PendingMessage(id:ref.id,conversationId:widget.chatId,text:text,createdAt:DateTime.now()));}catch(_){}}
  Future<void> _send()async{final text=_text.text.trim();if(text.isEmpty)return;final ref=_messages.doc();_text.clear();final data={'chatId':widget.chatId,'senderId':_uid,'senderName':FirebaseAuth.instance.currentUser?.displayName??'مستخدم','senderPhotoUrl':FirebaseAuth.instance.currentUser?.photoURL??'','text':text,'type':'text','status':'sent','isRead':false,'timestamp':FieldValue.serverTimestamp(),'clientTimestamp':Timestamp.now(),'replyToId':_reply?['id'],'replyPreview':_reply};setState(()=>_reply=null);try{await ref.set(data);await _db.collection('chats').doc(widget.chatId).set({'lastMessage':text,'lastMessageSenderId':_uid,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));}
  Future<void> _pickFile()async{if(_uploading)return;final result=await FilePicker.platform.pickFiles(withData:true);if(result==null||result.files.isEmpty)return;final file=result.files.first;final bytes=file.bytes;if(bytes==null)return;final mime=_mime(file.extension);setState(()=>_uploading=true);try{final uploaded=await _media.upload(bytes:bytes,filename:file.name,mimeType:mime,chatId:widget.chatId);final ref=_messages.doc();final type=mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':mime.startsWith('audio/')?'audio':'file';await ref.set({'chatId':widget.chatId,'senderId':_uid,'senderName':FirebaseAuth.instance.currentUser?.displayName??'مستخدم','text':type=='file'?file.name:'','type':type,'status':'sent','timestamp':FieldValue.serverTimestamp(),'clientTimestamp':Timestamp.now(),'fileUrl':uploaded.url,'fileName':file.name,'fileMimeType':mime,'fileSize':bytes.length,'isRead':false});await _db.collection('chats').doc(widget.chatId).set({'lastMessage':type=='image'?'📷 صورة':type=='video'?'🎬 فيديو':type=='audio'?'🎤 صوت':'📎 '+file.name,'lastMessageSenderId':_uid,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('فشل الرفع: $e')));}finally{if(mounted)setState(()=>_uploading=false);}}
  String _mime(String? ext){switch((ext??'').toLowerCase()){case 'jpg':case 'jpeg':return 'image/jpeg';case 'png':return 'image/png';case 'webp':return 'image/webp';case 'mp4':return 'video/mp4';case 'mov':return 'video/quicktime';case 'mp3':return 'audio/mpeg';case 'm4a':return 'audio/mp4';default:return 'application/octet-stream';}}
  void _call(bool video)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CallScreen(chatId:widget.chatId,otherUserId:widget.otherUserId,otherUserName:widget.otherUserName,otherUserImage:widget.otherUserImage,isVideo:video)));
  @override void dispose(){WidgetsBinding.instance.removeObserver(this);_typingTimer?.cancel();_text.dispose();_scroll.dispose();super.dispose();}
  @override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(backgroundColor:dark?const Color(0xFF0B1121):const Color(0xFFF4F7F7),appBar:AppBar(backgroundColor:const Color(0xFF0A8F83),foregroundColor:Colors.white,titleSpacing:0,title:Row(children:[CircleAvatar(radius:21,backgroundImage:widget.otherUserImage?.isNotEmpty==true?NetworkImage(widget.otherUserImage!):null,child:widget.otherUserImage?.isNotEmpty==true?null:const Icon(Icons.person)),const SizedBox(width:10),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.otherUserName,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w700)),_statusText()])]),actions:[IconButton(onPressed:()=>_call(false),icon:const Icon(Icons.call_outlined)),IconButton(onPressed:()=>_call(true),icon:const Icon(Icons.videocam_outlined))]),body:Column(children:[Expanded(child:_messagesView(dark)),_composer(dark)]));}
  Widget _statusText()=>StreamBuilder<DocumentSnapshot<Map<String,dynamic>>>(stream:_db.collection('users').doc(widget.otherUserId).snapshots(),builder:(context,s){final d=s.data?.data()??{};return Text(d['isOnline']==true?'متصل الآن':'غير متصل',style:const TextStyle(fontSize:11,color:Colors.white70));});
  Widget _messagesView(bool dark)=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:_messages.orderBy('timestamp',descending:true).limit(200).snapshots(),builder:(context,s){if(s.hasError)return Center(child:Text('تعذر تحميل الرسائل: '+s.error.toString()));if(!s.hasData)return const Center(child:CircularProgressIndicator(color:Color(0xFF0A8F83)));final docs=s.data!.docs;if(_uid.isNotEmpty){for(final doc in docs){final d=doc.data();if(d['senderId']!=_uid&&d['status']!='read'){doc.reference.update({'status':'read','readAt':FieldValue.serverTimestamp()}).catchError((_){ });}}}return ListView.builder(controller:_scroll,padding:const EdgeInsets.fromLTRB(12,16,12,12),reverse:true,itemCount:docs.length,itemBuilder:(context,i)=>_bubble(docs[i],dark));});
  Widget _bubble(DocumentSnapshot<Map<String,dynamic>> doc,bool dark){final d=doc.data()??{};final mine=d['senderId']==_uid;final type=d['type']?.toString()??'text';final url=d['fileUrl']?.toString();return GestureDetector(onLongPress:()=>setState(()=>_reply={'id':doc.id,'senderName':d['senderName']??'مستخدم','text':d['text']??'مرفق'}),child:Align(alignment:mine?AlignmentDirectional.centerEnd:AlignmentDirectional.centerStart,child:Container(constraints:const BoxConstraints(maxWidth:320),margin:const EdgeInsets.only(bottom:6),padding:const EdgeInsets.symmetric(horizontal:13,vertical:9),decoration:BoxDecoration(color:mine?const Color(0xFF0A8F83):(dark?const Color(0xFF162039):Colors.white),borderRadius:BorderRadius.only(topLeft:const Radius.circular(18),topRight:const Radius.circular(18),bottomLeft:Radius.circular(mine?18:4),bottomRight:Radius.circular(mine?4:18))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(d['replyPreview'] is Map)_replyBox(d,mine),if(type=='image'&&url!=null)ClipRRect(borderRadius:BorderRadius.circular(14),child:Image.network(url,width:260,height:220,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.broken_image,color:Colors.white70,size:48))),if(type=='video'||type=='audio'||type=='file')ListTile(contentPadding:EdgeInsets.zero,leading:Icon(type=='video'?Icons.play_circle_fill:type=='audio'?Icons.audiotrack:Icons.insert_drive_file,color:mine?Colors.white:const Color(0xFF0A8F83),size:36),title:Text(d['fileName']?.toString()??d['text']?.toString()??'مرفق',maxLines:2,overflow:TextOverflow.ellipsis,style:TextStyle(color:mine?Colors.white:(dark?Colors.white:Colors.black87))),onTap:()=>showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('رابط الوسائط'),content:SelectableText(url??'')))),if(type=='text')Text(d['text']?.toString()??'',style:TextStyle(color:mine?Colors.white:(dark?Colors.white:Colors.black87),fontSize:15)),const SizedBox(height:3),Row(mainAxisSize:MainAxisSize.min,children:[Text(_time(d['timestamp']),style:TextStyle(color:mine?Colors.white60:Colors.grey,fontSize:10)),if(mine)Padding(padding:const EdgeInsetsDirectional.only(start:5),child:Icon(d['status']=='read'?Icons.done_all:Icons.done,size:15,color:d['status']=='read'?Colors.lightBlueAccent:Colors.white70))])]))));}
  Widget _replyBox(Map<String,dynamic>d,bool mine){final r=d['replyPreview'] as Map;return Container(margin:const EdgeInsets.only(bottom:6),padding:const EdgeInsets.all(7),decoration:BoxDecoration(color:Colors.black12,borderRadius:BorderRadius.circular(9)),child:Text(r['text']?.toString()??'',maxLines:2,overflow:TextOverflow.ellipsis,style:TextStyle(color:mine?Colors.white70:Colors.black54,fontSize:11)));}
  String _time(dynamic value){if(value is Timestamp){final x=value.toDate();return x.hour.toString().padLeft(2,'0')+':'+x.minute.toString().padLeft(2,'0');}return '';}
  Widget _composer(bool dark)=>SafeArea(top:false,child:Column(children:[if(_reply!=null)Container(margin:const EdgeInsets.fromLTRB(10,4,10,0),padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:dark?const Color(0xFF162039):Colors.white,borderRadius:BorderRadius.circular(14)),child:Row(children:[const Icon(Icons.reply,color:Color(0xFF0A8F83)),const SizedBox(width:8),Expanded(child:Text(_reply?['text']?.toString()??'')),IconButton(onPressed:()=>setState(()=>_reply=null),icon:const Icon(Icons.close))])),Padding(padding:const EdgeInsets.fromLTRB(8,6,8,8),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(onPressed:_pickFile,icon:_uploading?const SizedBox(width:22,height:22,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.add_circle_outline,color:Color(0xFF0A8F83))),Expanded(child:TextField(controller:_text,minLines:1,maxLines:5,textDirection:TextDirection.rtl,decoration:InputDecoration(hintText:'اكتب رسالة...',filled:true,fillColor:dark?const Color(0xFF162039):Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(24),borderSide:BorderSide.none),contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:11)))),const SizedBox(width:5),IconButton.filled(onPressed:_send,style:IconButton.styleFrom(backgroundColor:const Color(0xFF0A8F83)),icon:const Icon(Icons.send_rounded))]))]));
}